default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: inakaikotto_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: inakaikotto_test

production:
  <<: *default
  database: inakaikotto_production
  username: inakaikotto
  password: <%= ENV['INAKAIKOTTO_DATABASE_PASSWORD'] %>
